# Generated by Django 3.1.5 on 2022-01-08 13:54

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#75715e', max_length=7, verbose_name='色(16進数)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_text',
            field=markdownx.models.MarkdownxField(help_text='Markdown形式で記入', verbose_name='本文'),
        ),
    ]
