# Generated by Django 3.1.5 on 2022-01-06 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Webサイトのタイトル', max_length=255, verbose_name='タイトル')),
                ('description', models.TextField(default='Webサイトの説明', max_length=255, verbose_name='サイトの説明')),
                ('keywords', models.CharField(default='Webサイトのキーワード', max_length=255, verbose_name='サイトのキーワード')),
                ('author', models.CharField(default='サイトの管理者', max_length=255, verbose_name='管理者')),
                ('email', models.EmailField(default='your_mail@gmail.com', max_length=255, verbose_name='管理者アドレス')),
                ('github', models.CharField(blank=True, max_length=255, verbose_name='Githubアカウント')),
                ('twitter', models.CharField(blank=True, max_length=255, verbose_name='Twitterアカウント')),
                ('facebook', models.CharField(blank=True, max_length=255, verbose_name='FaceBookアカウント')),
                ('google_ad_html', models.TextField(blank=True, verbose_name='アドセンスHTML')),
                ('google_analytics_html', models.TextField(blank=True, verbose_name='アナリティクスHTML')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sites.site', verbose_name='Site')),
            ],
        ),
    ]
