# Generated by Django 3.1.5 on 2022-01-07 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysiteinfo', '0002_auto_20220107_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedetail',
            name='titleimage',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='タイトル画像'),
        ),
    ]
