# Generated by Django 3.1.5 on 2022-01-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysiteinfo', '0003_sitedetail_titleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedetail',
            name='subtitle',
            field=models.CharField(default='Webサイトのサブタイトル', max_length=255, verbose_name='サブタイトル'),
        ),
    ]
