# Generated by Django 3.1.5 on 2022-01-08 13:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Webサイトのタイトル', max_length=255, verbose_name='タイトル')),
                ('titleimage', models.ImageField(blank=True, null=True, upload_to='', verbose_name='タイトル画像')),
                ('subtitle', models.CharField(default='Webサイトのサブタイトル', max_length=255, verbose_name='サブタイトル')),
                ('description', models.TextField(default='Webサイトの説明', max_length=255, verbose_name='サイトの説明')),
                ('keywords', models.CharField(default='Webサイトのキーワード', max_length=255, verbose_name='サイトのキーワード')),
                ('author', models.CharField(default='サイトの管理者', max_length=255, verbose_name='管理者')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='アバター')),
                ('birthdate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='生年月日')),
                ('job', models.CharField(default='管理者の職業', max_length=255, verbose_name='職業')),
                ('email', models.EmailField(default='your_mail@gmail.com', max_length=255, verbose_name='アドレス')),
                ('twitter', models.CharField(blank=True, max_length=255, verbose_name='Twitterアカウント')),
                ('google_analytics_html', models.TextField(blank=True, verbose_name='アナリティクスHTML')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sites.site', verbose_name='Site')),
            ],
        ),
    ]
